name: Documentation

on:
  release:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  build:
    name: "Build the documentation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.9'
      - name: Install SINs.jl
        run: julia --project=. -e 'using Pkg; Pkg.add(url="https://github.com/PoisotLab/SpeciesInteractionNetworks.jl")'
      - uses: julia-actions/julia-buildpkg@latest
      - name: Install documentation dependencies
        run: julia --project=docs -e 'using Pkg; pkg"dev ."; Pkg.add(url="https://github.com/PoisotLab/SpeciesInteractionNetworks.jl"); Pkg.instantiate(); Pkg.precompile(); Pkg.status()'
      #- name: Creating new mds from src
      - name: Build and deploy docs
        uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
          GKSwstype: "100" # for Plots.jl plots (if you have them)
          JULIA_DEBUG: "Documenter"
          DATADEPS_ALWAYS_ACCEPT: true
